/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-northeast-1",
  "aws_cognito_region": "ap-northeast-1",
  "oauth": {
      "domain": "skettt.auth.ap-northeast-1.amazoncognito.com",
      "scope": [
          "email",
          "openid"
      ],
      "redirectSignIn": "http://localhost:4200/oauth/cognito",
      "redirectSignOut": "http://localhost:4200/oauth/cognito",
      "responseType": "code"
  },
  "federationTarget": "COGNITO_USER_POOLS",
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": [
          "REQUIRES_LOWERCASE",
          "REQUIRES_UPPERCASE",
          "REQUIRES_NUMBERS",
          "REQUIRES_SYMBOLS"
      ]
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_region": "ap-northeast-1"
};


export default awsmobile;
